repo:
  public: ruby-eventsource

publications:
  - url: https://rubygems.org/gems/ld-eventsource
    description: RubyGems
  - url: https://www.rubydoc.info/gems/ld-eventsource
    description: documentation

releasableBranches:
  - name: master
    description: 2.x - based on the http gem
  - name: 1.x
    description: 1.x - based on the socketry gem

template:
  name: ruby
